const placesData = [
            {
                id: 1,
                name: "Old City (Icherisheher)",
                location: "Baku",
                category: "historical",
                description: "The historic core of Baku, a UNESCO World Heritage Site with medieval architecture, the Palace of the Shirvanshahs, and the iconic Maiden Tower. This ancient walled city dates back to at least the 12th century and offers a fascinating glimpse into Azerbaijan's rich history.",
                image: "https://imgs.search.brave.com/L6BudL7x2Gux45n2PSS08XQ1-yJ9ZC5JwgtuQdWjnSU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy8z/LzM0LyVDNCVCMCVD/MyVBNyVDOSU5OXJp/JUM1JTlGJUM5JTk5/aCVDOSU5OXJfMjAx/Ni5qcGc",
                coordinates: [40.3660, 49.8352],
                rating: 0,
                reviewCount: 0,
                hours: "Open 24/7",
                price: "Free",
                bestTime: "Spring and Autumn",
                tips: "Wear comfortable shoes for walking the cobblestone streets"
            },
            {
                id: 2,
                name: "Gobustan National Park",
                location: "Gobustan",
                category: "historical",
                description: "Famous for its rock petroglyphs and mud volcanoes, offering a unique glimpse into prehistoric human settlement. The park contains more than 6,000 rock engravings dating back between 5,000-40,000 years.",
                image: "https://imgs.search.brave.com/Qq1QJD107MO4ei5xaKIIXPkwQzOJc8MSm1S40lAMSUU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hay1k/LnRyaXBjZG4uY29t/L2ltYWdlcy8xbWkx/NDIyNHg4eGs0ZnZ5/dzVERTJfV182NDBf/MF9SNV9RODAuanBn/P3Byb2M9c291cmNl/L3RyaXA",
                coordinates: [40.1022, 49.3809],
                rating: 0,
                reviewCount: 0,
                hours: "9:00 AM - 5:00 PM",
                price: "10 AZN",
                bestTime: "Spring",
                tips: "Visit the museum first to understand the petroglyphs better"
            },
            {
                id: 3,
                name: "Heydar Aliyev Center",
                location: "Baku",
                category: "modern",
                description: "A stunning architectural masterpiece designed by Zaha Hadid, featuring flowing, curved styles that avoid sharp angles. The center hosts exhibitions, concerts, and conferences in its futuristic spaces.",
                image: "https://imgs.search.brave.com/PsOBdxYi8REQGYXS-XjuadJeHIHjGxq0BJrbKV5mLvs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTUw/MjIzNjkyNS9waG90/by9lZGl0b3JpYWwt/YmFrdS1oZXlkYXIt/YWxpeWV2LWNlbnRy/ZS5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9RmFvRENwcEI5/WTVRLVJzcDdYODFj/UmJseUxXNlZKcDZH/Y0NTQUJBX0pTYz0",
                coordinates: [40.3953, 49.8672],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 7:00 PM",
                price: "15 AZN",
                bestTime: "Evening for light shows",
                tips: "Book tickets online to avoid queues"
            },
            {
                id: 4,
                name: "Sheki Khan's Palace",
                location: "Sheki",
                category: "historical",
                description: "A magnificent 18th-century palace known for its exquisite stained glass windows and detailed frescoes. The palace was the summer residence of the Sheki Khans and showcases incredible craftsmanship.",
                image: "https://imgs.search.brave.com/-jqviagwuOqEdQwCN3D6nA7OPOGdG7ylGhGfN9TVQHg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS53bXNtLmNvLzY3/YmM3NGRmMGM5MDQv/cGFsYWNlLW9mLXNo/YWtpLWtoYW5zLndl/YnA_cXVhbGl0eT04/MCZ3aWR0aD04MDAm/aGVpZ2h0PTYwMCZh/c3BlY3RfcmF0aW89/ODAwOjYwMA",
                coordinates: [41.2035, 47.1825],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 6:00 PM",
                price: "5 AZN",
                bestTime: "Summer",
                tips: "Don't miss the beautiful Sheki halva while you're there"
            },
            {
                id: 5,
                name: "Yanar Dag (Fire Mountain)",
                location: "Absheron Peninsula",
                category: "natural",
                description: "A natural gas fire which blazes continuously on a hillside on the Absheron Peninsula, a mesmerizing natural phenomenon. The flames jet into the air 3 meters high from a thin, porous sandstone layer.",
                image: "https://imgs.search.brave.com/DLeiupiry1KPh8MXlkD8BlWOOWwCY3y9gnErJMRsv0A/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTc0/MDI0ODMwNy9waG90/by95YW5hci1kYWct/bmF0dXJhbC1maXJl/LWluLWF6ZXJiYWlq/YW4uanBnP3M9NjEy/eDYxMiZ3PTAmaz0y/MCZjPVJkTEp5eTBX/TmtXOXdEYlFlenJ5/T0NCT0xkbEk4dWFJ/RlJEck01YU5xMUE9",
                coordinates: [40.5142, 49.8904],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 7:00 PM",
                price: "8 AZN",
                bestTime: "Evening for best view of flames",
                tips: "Visit after sunset for the most dramatic effect"
            },
            {
                id: 6,
                name: "Gabala",
                location: "Gabala",
                category: "natural",
                description: "A picturesque mountain resort town with stunning landscapes, cable cars, and outdoor activities for all seasons. Gabala offers beautiful scenery, hiking trails, and the famous Tufandag Mountain Resort.",
                image: "https://imgs.search.brave.com/1bkPfHyVbb3FK_P24VQnLOxRGZ8w6cUIuoXdZjPzXPI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MTcvNDMvZWQvZTcv/Z2FiYWxhLmpwZw",
                coordinates: [40.9982, 47.8700],
                rating: 0,
                reviewCount: 0,
                hours: "Varies by attraction",
                price: "Varies",
                bestTime: "All seasons",
                tips: "Try the local cuisine at traditional restaurants"
            },
            {
                id: 7,
                name: "Ateshgah Fire Temple",
                location: "Surakhani",
                category: "cultural",
                description: "A temple built by fire-worshippers in Surakhany, showcasing the Zoroastrian history of the region. The temple was a place of worship for Zoroastrians.",
                image: "https://imgs.search.brave.com/6o_6nbupITsoZTpYO1YK0Fa2l3nlXMG6HoUxN300Wcg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNTY5/OTIyMzYxL3Bob3Rv/L2F0ZXNoZ2FoLXRl/bXBsZS1pbi1hemVy/YmFpamFuLmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz16bTRn/YXI0VG5sQXdyeDVX/Q3N4cGRzTl9KS09a/TnJ3YXFDQXBGb2Jn/c1NjPQ",
                coordinates: [40.4158, 50.0089],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 6:00 PM",
                price: "7 AZN",
                bestTime: "Afternoon",
                tips: "Combine your visit with Yanar Dag nearby"
            },
            {
                id: 8,
                name: "Nizami Street",
                location: "Baku",
                category: "modern",
                description: "A large pedestrian and shopping street in downtown Baku, known for its architecture and vibrant atmosphere. The street is lined with shops, cafes, and historic buildings, making it perfect for a leisurely stroll.",
                image: "http://eurasia.travel/wp-content/uploads/2025/03/9.-Nizami-street-Baku.jpg",
                coordinates: [40.3744, 49.8358],
                rating: 0,
                reviewCount: 0,
                hours: "Open 24/7",
                price: "Free",
                bestTime: "Evening",
                tips: "Visit in the evening when the street comes alive with lights and people"
            },
            {
                id: 9,
                name: "Shahdag Mountain Resort",
                location: "Gusar",
                category: "natural",
                description: "Azerbaijan's premier winter sports destination with modern facilities for skiing, snowboarding, and other mountain activities. The resort offers breathtaking views of the Greater Caucasus mountains.",
                image: "https://imgs.search.brave.com/xYUFB01F3ceZXutg9goaMqqrofVgEklbTpz2ewStm9w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kM3cx/M241M2ZvYXNlNy5j/bG91ZGZyb250Lm5l/dC9odHRwczovL2l0/aW5hcmktaW1hZ2Vz/LnMzLmV1LXdlc3Qt/MS5hbWF6b25hd3Mu/Y29tL2FjdGl2aXR5/L2ltYWdlcy9vcmln/aW5hbC9hZDVhNjIw/Mi0wYTdkLTQ4ZGIt/YjZlYS04YTg1NGEw/MmU2ZWEtY29udGFj/dC5qcGdfaW1hZ2Uu/anBn",
                coordinates: [41.3256, 48.2056],
                rating: 0,
                reviewCount: 0,
                hours: "9:00 AM - 5:00 PM",
                price: "Varies by activity",
                bestTime: "December to March",
                tips: "Book equipment rental in advance during peak season"
            },
            {
                id: 10,
                name: "Mud Volcanoes of Gobustan",
                location: "Gobustan",
                category: "natural",
                description: "One of the most impressive collections of mud volcanoes in the world, with over 300 of Azerbaijan's 700 mud volcanoes located here. The landscape feels otherworldly with bubbling mud and occasional eruptions.",
                image: "https://imgs.search.brave.com/iW7e86_JWyiAjTQOfFJPcWLl4763u0Of2qZlgWof6DM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHJhdmVsYWR2ZW50/dXJlcy5vcmcvY291/bnRyaWVzL2F6ZXJi/YWlqYW4vaW1hZ2Vz/L2dvYnVzdGFuLW11/ZC12b2xjYW5vZXMw/NC5qcGc",
                coordinates: [40.1056, 49.3800],
                rating: 0,
                reviewCount: 0,
                hours: "8:00 AM - 6:00 PM",
                price: "5 AZN",
                bestTime: "Spring and Autumn",
                tips: "Wear waterproof shoes as the ground can be muddy"
            },
            {
                id: 11,
                name: "Bibi-Heybat Mosque",
                location: "Baku",
                category: "cultural",
                description: "A historical mosque reconstructed in the 1990s, originally built in the 13th century. The mosque is an important pilgrimage site and features stunning Islamic architecture with three domes and two minarets.",
                image: "https://imgs.search.brave.com/pdeRgYrnVoLbCS9rgd3GZj-T_p_jgKb5QO6ls78Ui7Y/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDgvY2YvMjEvOWMv/Y2FwdGlvbi5qcGc",
                coordinates: [40.3072, 49.8208],
                rating: 0,
                reviewCount: 0,
                hours: "8:00 AM - 8:00 PM",
                price: "Free",
                bestTime: "All year",
                tips: "Dress modestly and women should cover their heads"
            },
            {
                id: 12,
                name: "Lahij Village",
                location: "Ismayilli",
                category: "natural",
                description: "An ancient mountain village famous for its copper craftsmanship, cobbled streets, and traditional architecture. Lahij has been a center of craftsmanship for over 1,000 years.",
                image: "https://imgs.search.brave.com/a67tOyUu7fjoOyjWOCvmDu6dcN2PHuzAuKyhk5O2Ruo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vcGhvdG9z/L21vdW50YWluLXZp/bGxhZ2UtbGFoaWot/bG9jYXRlZC1pbi1u/b3J0aC1hemVyYmFp/amFuLWF0LWVhcmx5/LW1vcm5pbmctcGlj/dHVyZS1pZDExNjA1/MjQwMjQ_az0yMCZt/PTExNjA1MjQwMjQm/cz02MTJ4NjEyJnc9/MCZoPV9adnJSeVc2/bDdYQk5fZTRPQlBz/WllMeDNKMENleUpL/SVVmeWVFNmtRQVE9",
                coordinates: [40.8531, 48.3819],
                rating: 0,
                reviewCount: 0,
                hours: "Open 24/7",
                price: "Free",
                bestTime: "Spring to Autumn",
                tips: "Buy authentic copperware directly from local craftsmen"
            },
            {
                id: 13,
                name: "Flame Towers",
                location: "Baku",
                category: "modern",
                description: "Baku's most iconic modern landmark, three skyscrapers shaped like flames that illuminate with LED displays at night. The towers house hotels, apartments, and offices and symbolize Azerbaijan's nickname 'Land of Fire'.",
                image: "https://imgs.search.brave.com/skagmVHMNmqFSWB6lzym_DsViG8OAFvYrfRggHEWucQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLmlt/Z3VyLmNvbS9FRzM5/cmw3LmpwZw",
                coordinates: [40.3592, 49.8281],
                rating: 0,
                reviewCount: 0,
                hours: "24/7 (exterior view)",
                price: "Free (exterior)",
                bestTime: "Evening for light show",
                tips: "Visit the nearby Highland Park for the best photo opportunities"
            },
            {
                id: 14,
                name: "Goygol Lake",
                location: "Goygol",
                category: "natural",
                description: "A stunning turquoise lake formed after an earthquake in 1139, located in the Goygol National Park. The lake is surrounded by dense forests and offers pristine natural beauty.",
                image: "https://imgs.search.brave.com/Ds1icxhCyvw-gnZSArb42y-tfjfbBMxv_JwCNfG0ptw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHJhdmVsbmFncy5j/b20vdXBsb2FkL2Rl/c3RpbmF0aW9ucy82/NWUxNzg0NTgxYmZm/X2dveWdvbDIlMjAo/MSkuanBn",
                coordinates: [40.4047, 46.3269],
                rating: 0,
                reviewCount: 0,
                hours: "8:00 AM - 6:00 PM",
                price: "3 AZN",
                bestTime: "May to September",
                tips: "Bring a picnic and enjoy the scenic surroundings"
            },
            {
                id: 15,
                name: "Palace of Happiness",
                location: "Baku",
                category: "historical",
                description: "Also known as the Palace of Weddings, this beautiful building was constructed in the early 20th century and features exquisite Gothic and Baroque architectural elements.",
                image: "https://imgs.search.brave.com/PG6tWNhQ5pK2P6daSx-jnKemMOMxWVSsLcrOgoQOc8c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/YXplcm5ld3MuYXov/bWVkaWEvMjAxOS8w/OC8wOS9kdm9yZWMt/bXVodGFyb3ZhLmpw/Zw",
                coordinates: [40.3714, 49.8353],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 6:00 PM",
                price: "Free (exterior only)",
                bestTime: "Daytime",
                tips: "The interior can be visited during wedding registration hours"
            },
            {
                id: 16,
                name: "Nohur Lake",
                location: "Gabala",
                category: "natural",
                description: "A picturesque artificial lake surrounded by mountains and forests, perfect for relaxation and nature photography. The lake offers boating facilities and walking trails.",
                image: "https://imgs.search.brave.com/RD3KS-VBHxV7eZHCdAMR-fWSWfkOiX5suwn4usUf4fo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdG9y/YWdlLmdvb2dsZWFw/aXMuY29tL3N0YXRl/bGVzcy13d3ctanVz/dHdyYXZlbC1jb20v/MjAyNS8wNS85ODE0/NDBjYS0xMC5qcGc",
                coordinates: [40.9319, 47.8319],
                rating: 0,
                reviewCount: 0,
                hours: "9:00 AM - 7:00 PM",
                price: "2 AZN",
                bestTime: "Spring and Summer",
                tips: "Try the local trout at restaurants near the lake"
            },
            {
                id: 17,
                name: "Azerbaijan Carpet Museum",
                location: "Baku",
                category: "cultural",
                description: "Housed in a building shaped like a rolled carpet, this museum showcases the ancient art of Azerbaijani carpet weaving with over 10,000 exhibits dating from ancient times to present.",
                image: "https://imgs.search.brave.com/yvHWumC1iA4fH2ree3WdcbEDvd6BvpsQde3-z08WfH8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly92aXNh/Zm9yYXplcmJhaWph/bi5vcmcudWsvd3At/Y29udGVudC91cGxv/YWRzL2F6ZXJiYWlq/YW4tY2FycGV0LW11/c2V1bS1leGhpYml0/aW9uLmpwZw",
                coordinates: [40.3583, 49.8342],
                rating: 0,
                reviewCount: 0,
                hours: "10:00 AM - 6:00 PM",
                price: "10 AZN",
                bestTime: "All year",
                tips: "Join a guided tour to better understand the symbolism in the carpets"
            },
            {
                id: 18,
                name: "Tufandag Mountain Resort",
                location: "Gabala",
                category: "natural",
                description: "A year-round mountain resort offering skiing in winter and hiking, cable car rides, and outdoor activities in summer. The resort features one of the longest cable car systems in the world.",
                image: "https://imgs.search.brave.com/xQACgpxNCsPbIDZgtVQNUXvnvkcOjqVyZEyqJ_O4sE0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hay1k/LnRyaXBjZG4uY29t/L2ltYWdlcy8wSEow/bDEyMDAwaDBmdXJk/NUQ2Q0FfV18xNDQw/XzgxMF9RODAud2Vi/cD9wcm9jPXNvdXJj/ZS90cmlwJnByb2M9/c291cmNlL3RyaXA",
                coordinates: [40.9986, 47.8358],
                rating: 0,
                reviewCount: 0,
                hours: "9:00 AM - 5:00 PM",
                price: "Varies by activity",
                bestTime: "Winter for skiing, Summer for hiking",
                tips: "Buy cable car tickets online to avoid long queues"
            },
            {
                id: 19,
                name: "Shirvan National Park",
                location: "Salyan",
                category: "natural",
                description: "A protected area featuring semi-desert landscapes, salt marshes, and important bird habitats. The park is home to gazelles, jackals, and over 100 species of birds.",
                image: "https://imgs.search.brave.com/eKiNoRBzpObPNKtGUTiiQwSRXFdk-t0mH7ZiGx4UaqM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9uYXRp/b25hbHBhcmtzYXNz/b2NpYXRpb24ub3Jn/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDI0/LzA4L0hpcmthbi1O/YXRpb25hbC1QYXJr/LmpwZw",
                coordinates: [39.5531, 49.0156],
                rating: 0,
                reviewCount: 0,
                hours: "8:00 AM - 5:00 PM",
                price: "5 AZN",
                bestTime: "Spring and Autumn",
                tips: "Bring binoculars for bird watching"
            },
            {
                id: 20,
                name: "Baku Boulevard",
                location: "Baku",
                category: "modern",
                description: "A picturesque promenade running parallel to Baku's seafront, featuring beautiful parks, fountains, amusement rides, and stunning views of the Caspian Sea. The boulevard stretches for 3.75 km and is a favorite leisure spot for both locals and tourists.",
                image: "https://imgs.search.brave.com/kMfeDOrNsGH2lvrtlBYiQSFLOtvoClNdGbwXuVCjlEg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jYWNo/ZS5tYXJyaW90dC5j/b20vaXMvaW1hZ2Uv/bWFycmlvdHRzN3By/b2QvbWMtZ3lkbWIt/ZGVzdGluYXRpb24t/MTUwNjU6Q2xhc3Np/Yy1Ib3I_d2lkPTQz/MCZmaXQ9Y29uc3Ry/YWlu",
                coordinates: [40.3676, 49.8372],
                rating: 0,
                reviewCount: 0,
                hours: "Open 24/7",
                price: "Free",
                bestTime: "Evening for sunset views",
                tips: "Rent a bicycle or electric scooter to explore the entire length"
            },
            {
                id: 21,
                name: "Chinar Hotel & Spa",
                location: "Shamakhi",
                category: "natural",
                description: "A luxurious mountain resort nestled in the picturesque landscapes of Shamakhi, offering thermal springs, spa treatments, and breathtaking views of the Caucasus Mountains. The resort combines modern comfort with traditional Azerbaijani hospitality.",
                image: "https://imgs.search.brave.com/iPLXz1qXEP2YT0wQREwY7iLOFdYLJnSLcZhEbtlaorw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZi5i/c3RhdGljLmNvbS94/ZGF0YS9pbWFnZXMv/aG90ZWwvbWF4MTAy/NHg3NjgvNDQ3ODM3/MTQ1LmpwZz9rPTcx/ZjEyN2I2OGM2ZDQz/ZDE3YmYyZTIxYjlk/ZTQxNjE0NmM2ODFl/Y2NiZTg5NjYxOTY3/ZDhjZDMwMTU2ZGMz/NTAmbz0maHA9MQ",
                coordinates: [40.6314, 48.6414],
                rating: 0,
                reviewCount: 0,
                hours: "24/7",
                price: "Luxury resort - varies by package",
                bestTime: "All year round",
                tips: "Book spa treatments in advance, especially during weekends"
            }
];

// Global app state
const appState = {
    currentUser: JSON.parse(localStorage.getItem('currentUser')) || null,
    users: JSON.parse(localStorage.getItem('users')) || [],
    places: [],
    favorites: JSON.parse(localStorage.getItem('favorites')) || [],
    reviews: JSON.parse(localStorage.getItem('reviews')) || {},
    currentPlace: null
};